import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Search, Loader2, Sparkles, Bot } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { Input } from "@/components/ui/input";
import type { Lead } from "./leads";

export const Route = createFileRoute("/ai-replies")({
  head: () => ({
    meta: [
      { title: "AI Replies — JobFlow AI" },
      { name: "description", content: "All AI-generated replies sent to your leads." },
    ],
  }),
  component: Page,
});

function Page() {
  const { user } = useAuth();
  const [leads, setLeads] = useState<Lead[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  useEffect(() => {
    if (!user) return;
    let cancelled = false;
    (async () => {
      setLoading(true);
      const { data } = await supabase
        .from("leads")
        .select("*")
        .not("ai_reply", "is", null)
        .order("created_at", { ascending: false });
      if (cancelled) return;
      setLeads((data ?? []) as Lead[]);
      setLoading(false);
    })();
    return () => { cancelled = true; };
  }, [user]);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return leads;
    return leads.filter((l) =>
      [l.full_name, l.email, l.property_interest, l.ai_reply]
        .filter(Boolean)
        .some((v) => v!.toLowerCase().includes(q)),
    );
  }, [leads, search]);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">AI Replies</h1>
        <p className="text-sm text-muted-foreground">
          {leads.length} reply{leads.length === 1 ? "" : "ies"} sent
        </p>
      </div>

      <div className="relative max-w-md">
        <Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
        <Input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search lead, email, property, reply…"
          className="pl-9"
        />
      </div>

      {loading ? (
        <div className="rounded-xl border border-border bg-card p-12 flex items-center justify-center text-muted-foreground">
          <Loader2 className="h-5 w-5 animate-spin mr-2" /> Loading replies…
        </div>
      ) : filtered.length === 0 ? (
        <div className="rounded-xl border border-dashed border-border bg-card p-12 text-center">
          <div className="mx-auto h-12 w-12 rounded-full bg-muted flex items-center justify-center mb-3">
            <Bot className="h-5 w-5 text-muted-foreground" />
          </div>
          <p className="text-sm font-medium text-foreground">
            {leads.length === 0 ? "No AI replies yet" : "No replies match your search"}
          </p>
          <p className="text-sm text-muted-foreground mt-1">
            {leads.length === 0
              ? "Replies generated by your AI will appear here."
              : "Try a different search term."}
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map((l) => (
            <div key={l.id} className="rounded-xl border border-border bg-card p-5 shadow-[var(--shadow-card)]">
              <div className="flex flex-wrap items-start justify-between gap-2 mb-3">
                <div>
                  <h3 className="font-semibold text-foreground">{l.full_name ?? "Unnamed lead"}</h3>
                  <div className="text-xs text-muted-foreground mt-0.5 flex flex-wrap gap-x-3 gap-y-1">
                    {l.email && <span>{l.email}</span>}
                    {l.property_interest && <span>· {l.property_interest}</span>}
                  </div>
                </div>
                <span className="text-xs text-muted-foreground whitespace-nowrap">
                  {new Date(l.created_at).toLocaleString()}
                </span>
              </div>
              <div className="rounded-lg border border-primary/20 bg-primary/5 p-4">
                <div className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wider text-primary mb-2">
                  <Sparkles className="h-3.5 w-3.5" /> AI reply
                </div>
                <p className="text-sm text-foreground whitespace-pre-wrap">{l.ai_reply}</p>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
